### ISSUE TITLE
Repository https://artifact.fit.fraunhofer.de/repository/ids-public/ Temporarily Unavailable

### ISSUE THREAD

**Issue by alzcurda** [International-Data-Spaces-Association/IDS-AppStore#124]
**Describe the bug**
During Docker generation the process fail with the error:

#0 97.36 [ERROR] Failed to execute goal on project appstore: Could not resolve dependencies for project de.fraunhofer.fit:appstore:jar:4.1.0: Failed to collect dependencies at ids.messaging:broker:jar:7.0.0 -> ids.messaging:messagin
g:jar:7.0.0 -> ids.messaging:core:jar:7.0.0 -> de.fraunhofer.iais.eis.ids:infomodel-serializer:jar:4.2.8 -> de.fraunhofer.iais.eis.infomodel:util:jar:4.2.7-SNAPSHOT: Failed to read artifact descriptor for de.fraunhofer.iais.eis.info
model:util:jar:4.2.7-SNAPSHOT: Could not transfer artifact de.fraunhofer.iais.eis.infomodel:util:pom:4.2.7-SNAPSHOT from/to fit-nexus-public (https://artifact.fit.fraunhofer.de/repository/ids-public/): transfer failed for https://artifact.fit.fraunhofer.de/repository/ids-public/de/fraunhofer/iais/eis/infomodel/util/4.2.7-SNAPSHOT/util-4.2.7-SNAPSHOT.pom, status: 503 Service Temporarily Unavailable -> [Help 1]

**To Reproduce**
Go to root project code and run:
docker compose -f docker-compose.yml up --build -d 

**Expected behavior**
Docker instance will be created and running.

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/53859497/214348555-2b537469-762b-4889-ae3c-c6499493dbb4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version IDS-Appstore: main

**Additional context**
I guess the server is down. There are some prevision to get it up?

**Comment by SebastianOpriel** [comment]
@timwirtz86

**Comment by SebastianOpriel** [comment]
@timwirtz86 do you know, who can help with Artifactory at FIT?

**Comment by timwirtz86** [comment]
@SebastianOpriel sadly not, but why not using the artifactory of IAIS? you should find all artifacts there https://maven.iais.fraunhofer.de/ui/native/eis-ids-public/

**Comment by alzcurda** [comment]
@timwirtz86 I replaced

<url>https://artifact.fit.fraunhofer.de/repository/ids-public/</url>

for:
<url>https://maven.iais.fraunhofer.de/ui/native/eis-ids-public/</url>

<img width="384" alt="image" src="https://user-images.githubusercontent.com/53859497/215516824-fad6fdba-7ce2-4585-8937-2635b573fae9.png">

But now I am having several missing errors:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/53859497/215517195-5153dafb-5ae3-4168-8d9b-9f13a2b0b611.png">

I am using the main version of AppStore's POM:

https://github.com/International-Data-Spaces-Association/IDS-AppStore/blob/2b9b612a463a965187b444035d0b3f93d29e7904/pom.xml#L552-L562

Am I using the correct version?

Thank you for all.

**Comment by boxer-code** [comment]
I'm facing the same issue and it seems like the naming of the artifacts at the iais repo could be different? Are there any updates or quick fixes yet? Thanks in advance!

**Comment by alzcurda** [comment]
It appears that the server is up again. I was able to build docker image again, but I think that there is some kind of access problem becouse the proccess lasted about 30 minutes.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/53859497/219430695-b26ee7d9-3bb9-4a70-add0-ce742f846710.png">
