### ISSUE TITLE
Implementation of DataApps and Catalogs endpoints

### ISSUE THREAD

**Issue by rizktouma** [International-Data-Spaces-Association/IDS-AppStore#44]
**Is your feature request related to a problem? Please describe.**
The current version of the AppStore open source code (v2.0.0) has a lot of endpoints documented in Swagger but not implemented. Specifically, the DataApps and Catalogs endpoints which are needed for communication with the Dataspace Connector are not implemented.

**Describe the solution you'd like**
Ideally, these endpoints should be implemented to allow for communication with the Dataspace Connector as per the [documentation ](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/docs/pages/communication/v6/ecosystem/appStore.md) provided in its repository. It seems that the AppStore instance mentioned in the documentation (https://binac.fit.fraunhofer.de) does have these endpoints implemented, but it is currently not accessible.

**Describe alternatives you've considered**
The alternative we are considering is implementing the needed endpoints ourselves. However, this will most likely create some conflicts when a new version of the AppStore is pushed to the repository with these functionalities implemented. Is it planned to implement any of these AppStore endpoints in the next months?

**Additional context**
We are planning to use the IDS AppStore in a research project we are currently working on in the i2CAT Foundation in Barcelona. We have already used the Trusted Connector in other projects and we are members of IDSA.

**Comment by ahemaid** [comment]
Hi @rizktouma, 
I would like to ask to try again since we were working on binac.fit.fraunhofer.de server and it was stopped for a while. 
But now it is running. Please also have a look on our new docs [here](https://international-data-spaces-association.github.io/IDS-AppStore/)
