### ISSUE TITLE
Non-trackable documentation

### ISSUE THREAD

**Issue by jfernandezsqs** [International-Data-Spaces-Association/IDS-AppStore#54]
At the documentation (https://international-data-spaces-association.github.io/IDS-AppStore/deployment/configuration#configuration-of-harbor-registry-and-app-store) I do not know if the configuration I am using for the App Store and the Harbor Registry is correct.
First, I am having issues with the HTTPS configuration of harbor (https://github.com/International-Data-Spaces-Association/IDS-AppStore/issues/53) and the documentation provided for the configuration:

![image](https://user-images.githubusercontent.com/82888094/150147381-23b31b06-fcae-4c78-8bd7-4b729cd3d8ad.png)

Here I have doubts with the endpointURL format that is necessary for the library project webhook and with the registry URL needed to specify at the App Store application.properties file.
Could you include in the documentation a local deployment example for the Configuration of Harbor Registry and App Store?

**Comment by ahemaid** [comment]
Hi @jfernandezsqs, 
First of all, it is better to have Harbor Registry on a host which has a domain name, otherwise, you will face such a problem. Also, we have tried Harbor Registry locally (using DNS) with HTTP. I would say for HTTPS you need to have proper and valid SSL certificates.
