### ISSUE TITLE
compilation failes because of wrong import

### ISSUE THREAD

**Issue by RasmusAntons** [International-Data-Spaces-Association/IDS-AppStore#61]
b0d8438 changes the base class from BaseResourceChildRestrictedController to BaseResourceChildController but does not update the import in line 21.
Following the build instructions fails with the this message:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project appstore: Compilation failure
[ERROR] /home_local/rasmus/ids-appstore/IDS-AppStore/src/main/java/io/dataspaceconnector/controller/resource/relation/ResourcesToContractsController.java:[37,53] cannot find symbol
[ERROR]   symbol: class BaseResourceChildController
```
Changing line 21 of `src/main/java/io/dataspaceconnector/controller/resource/relation/ResourcesToContractsController.java` to `import io.dataspaceconnector.controller.resource.base.BaseResourceChildController;` solves the issue.

**Comment by ahemaid** [comment]
Yes, that we have do offline. But it is needed also the import line. 
Thanks.
