### ISSUE TITLE
Error when using Docker-compose

### ISSUE THREAD

**Issue by AnaCarolinaChaves** [International-Data-Spaces-Association/IDS-AppStore#78]
When running the create_resources_and_upload_app_local.py script with the jar file, everything works fine, and I'm able to publish an app. However, when using a docker-compose the URLs routes lack the port. The same is happening when using the Swagger UI. 

The create_resources_and_upload_app_local.py script logs, with the docker-compose are:
'[https://HOST/api/catalogs/21a01a10-f655-4982-a8a5-c7468ddf674d](https://%3Chost%3E/api/catalogs/21a01a10-f655-4982-a8a5-c7468ddf674d)'
'[https:/HOST/api/resources/8455c917-85ac-46f5-bcdb-1828b005565f](https://%3Chost%3E/api/resources/8455c917-85ac-46f5-bcdb-1828b005565f)'

With the jar file are:
'[https://HOST:9443/api/catalogs/836dc8bd-7384-4131-9c97-2c444d2a795d](https://%3Chost%3E:9443/api/catalogs/836dc8bd-7384-4131-9c97-2c444d2a795d)'
'[https://HOST:9443/api/resources/3b7714e4-459d-43a1-aa05-6e39f780ca70](https://%3Chost%3E:9443/api/resources/3b7714e4-459d-43a1-aa05-6e39f780ca70)'

I'm using Harbor with HTTPS on the same machine as the AppStore.

**Comment by boxer-code** [comment]
Hi, I'm currently facing the same error. Did you fix it with Harbor and AppStore on the same machine? Thanks in advance!

**Comment by AnaCarolinaChaves** [comment]
Hi!
I solved it by updating the provided` nginx.conf` file.

I replaced all the following lines: 
```proxy_set_header   Host               $host;```
with 
```proxy_set_header   Host                 $http_host;```

I hope this helps!!
