### ISSUE TITLE
Artifact LocalData encoding issues

### ISSUE THREAD

**Issue by ftgy** [International-Data-Spaces-Association/IDS-AppStore#85]
**Describe the bug**
There are encoding issues related to the LocalData of an Artifact.

From the appstore side, in `io.dataspaceconnector.model.artifact.ArtifactFactory#updateLocalData()` the LocalData value is encoded in StandardCharsets.UTF_16 before being stored in database. 
When the connector gets the app metadata and stores it in `io.dataspaceconnector.service.EntityPersistenceService#saveAppData()` 
StandardCharsets.UTF_8 is used to decode the string, generating garbage values.

To fix this, we need to change the character encoding on the appstore side or the connector side.

![image (1)](https://user-images.githubusercontent.com/16019124/173809331-ce48e453-31d8-49bb-9d1f-f4604372054c.png)

**Comment by ahemaid** [comment]
Hi @ftgy , 

I can see that this is an old issue, could you please try with the branch dsc7upgrade. I would like to know if there issue still exist.
