### ISSUE TITLE
Error Quick Start

### ISSUE THREAD

**Issue by katsurak90** [International-Data-Spaces-Association/IDS-AppStore#87]
**Describe the bug**
I ran the command using the 'QuickStart' procedure as a reference.  
However, I confirmed an error output.
Could you please let me know how to solve this problem?

**To Reproduce**
1. git clone https://github.com/International-Data-Spaces-Association/IDS-AppStore.git
2. cd / && mkdir -p /data/search
3. cd IDS-AppStore && chmod +x mvnw
4. ./mvnw clean package -DskipTests -Dmaven.javadoc.skip=true ← ERROR!!!

**Screenshots & Logs**

```
$ ./mvnw clean package -DskipTests -Dmaven.javadoc.skip=true
./mvnw: line 276: /home/ec2-user/IDS-AppStore/.mvn/wrapper/maven-wrapper.properties: No such file or directory
/home/ec2-user/IDS-AppStore/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```

**Desktop (please complete the following information):**

- OS

  ```shell
  $ cat /etc/os-release

  NAME="Amazon Linux"
  VERSION="2"
  ID="amzn"
  ID_LIKE="centos rhel fedora"
  VERSION_ID="2"
  PRETTY_NAME="Amazon Linux 2"
  ANSI_COLOR="0;33"
  CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
  HOME_URL="https://amazonlinux.com/"
  ```

- java version

  ```shell
  $ java --version

  openjdk 11.0.13 2021-10-19 LTS
  OpenJDK Runtime Environment 18.9 (build 11.0.13+8-LTS)
  OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8-LTS, mixed mode, sharing)
  ```

**Additional context**

**Comment by boxer-code** [comment]
Hi I'm facing the same error right now. How did you fix it? Thanks in advance!
