### ISSUE TITLE
Missing artifact  "de.fraunhofer.ids.messaging:broker:jar:5.1.1 in Maven repository (https://repo1.maven.org/maven2/)"

### ISSUE THREAD

**Issue by boxer-code** [International-Data-Spaces-Association/IDS-AppStore#99]
**Describe the bug**
During the Quick Start the maven build fails with the error: 
````
[ERROR] Failed to execute goal on project appstore: Could not resolve dependencies for project de.fraunhofer.fit:appstore:jar:2.0.0: Could not find artifact de.fraunhofer.ids.messaging:broker:jar:5.1.1 in Maven repository (https://repo1.maven.org/maven2/)
`````

**To Reproduce**
Steps to reproduce the behavior (Quick Start):
1. Clone the repository
2. I've added a .mvn folder with the maven wrapper
3. Execute cd IDS-AppStore, chmod +x mvnw and ./mvnw clean package -DskipTests -Dmaven.javadoc.skip=true

**Expected behavior**
The build is successful and a executable jar is created.

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/65717371/195075787-2e46a8ff-cb29-4c7d-a2f3-32c3e0c5023c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Latest version of the appstore

**Comment by SebastianOpriel** [comment]
Seems to be related to https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/453

**Comment by ahemaid** [comment]
This has been fixed in the latest version
